Repository sonic-net/sonic-swss-common, pull requests merged in 2018-04, with the labels that each got.

#193 Fix a bug which caused SAI use unintialized log levels
  common/logger.cpp
Labels: bug

#190 Add map of database ID -> table name separator; No longer pass table name separator when constructing Table objects
  common/consumertablebase.cpp
  common/dbconnector.cpp
  common/dbconnector.h
  common/notificationconsumer.cpp
  common/producerstatetable.cpp
  common/producertable.cpp
  common/redispipeline.h
  common/subscriberstatetable.cpp
  common/table.cpp
  common/table.h
  tests/redis_piped_ut.cpp
  tests/redis_subscriber_state_ut.cpp
  tests/redis_ut.cpp
  tests/test_redis_ut.py
Labels: enhancement

#194 Make C++ Unit Tests work with recent table name separator changes
  tests/json_ut.cpp
  tests/redis_piped_state_ut.cpp
  tests/redis_piped_ut.cpp
  tests/redis_state_ut.cpp
  tests/redis_subscriber_state_ut.cpp
Labels: bug

#195 Fix the C++ unit tests. Use more specific EXPECT_ clauses
  tests/exec_ut.cpp
  tests/json_ut.cpp
  tests/ntf_ut.cpp
  tests/redis_piped_state_ut.cpp
  tests/redis_state_ut.cpp
  tests/redis_subscriber_state_ut.cpp
Labels: enhancement

#192 Refactor Selectables. Add support for selectable priorities
  common/consumerstatetable.cpp
  common/consumerstatetable.h
  common/consumertable.cpp
  common/consumertable.h
  common/consumertablebase.cpp
  common/consumertablebase.h
  common/logger.cpp
  common/netlink.cpp
  common/netlink.h
  common/notificationconsumer.cpp
  common/notificationconsumer.h
  common/rediscommand.cpp
  common/redisselect.cpp
  common/redisselect.h
  common/select.cpp
  common/select.h
  common/selectable.h
  common/selectableevent.cpp
  common/selectableevent.h
  common/selectabletimer.cpp
  common/selectabletimer.h
  common/subscriberstatetable.cpp
  common/subscriberstatetable.h
  common/table.h
  tests/Makefile.am
  tests/ntf_ut.cpp
  tests/redis_piped_state_ut.cpp
  tests/redis_piped_ut.cpp
  tests/redis_state_ut.cpp
  tests/redis_subscriber_state_ut.cpp
  tests/redis_ut.cpp
  tests/selectable_priority.cpp
  tests/test_redis_ut.py
Labels: bug, enhancement

#196 [rules]: Clean pyext/*.py files in dh_clean
  debian/rules
Labels: enhancement

#197 Pass arguments by references for constructors and methods
  common/consumerstatetable.cpp
  common/consumerstatetable.h
  common/consumertable.cpp
  common/consumertable.h
  common/consumertablebase.cpp
  common/consumertablebase.h
  common/converter.h
  common/dbconnector.cpp
  common/dbconnector.h
  common/ipaddress.cpp
  common/ipaddresses.cpp
  common/logger.cpp
  common/logger.h
  common/loglevel.cpp
  common/notificationconsumer.cpp
  common/notificationconsumer.h
  common/notificationproducer.cpp
  common/notificationproducer.h
  common/portmap.cpp
  common/portmap.h
  common/producerstatetable.cpp
  common/producerstatetable.h
  common/producertable.cpp
  common/producertable.h
  common/redisclient.cpp
  common/redisclient.h
  common/redisreply.cpp
  common/redisreply.h
  common/redisselect.cpp
  common/redisselect.h
  common/redistran.cpp
  common/redistran.h
  common/subscriberstatetable.cpp
  common/subscriberstatetable.h
  common/table.cpp
  common/table.h
Labels: enhancement
