Repository sonic-net/sonic-swss-common, pull requests merged in 2019-09, with the labels that each got.

#284 Add sub interface CONFIG_DB schema
  common/schema.h
Labels: enhancement

#302 timerfd return 0 with errno =0 - handle as False alarm.
  common/netlink.cpp
  common/netlink.h
  common/notificationconsumer.cpp
  common/notificationconsumer.h
  common/redisselect.cpp
  common/redisselect.h
  common/selectable.h
  common/selectableevent.cpp
  common/selectableevent.h
  common/selectabletimer.cpp
  common/selectabletimer.h
  common/subscriberstatetable.cpp
  common/subscriberstatetable.h
Labels: Request for 201811 branch, bug

#307 timerfd fix: Pass false alarm to caller.
  common/netlink.cpp
  common/netlink.h
  common/notificationconsumer.cpp
  common/notificationconsumer.h
  common/redisselect.cpp
  common/redisselect.h
  common/selectable.h
  common/selectableevent.cpp
  common/selectableevent.h
  common/selectabletimer.cpp
  common/selectabletimer.h
  common/subscriberstatetable.cpp
  common/subscriberstatetable.h
Labels: bug
