Repository sonic-net/sonic-swss-common, pull requests merged in 2019-02, with the labels that each got.

#259 [pyext] enable types in stdint.h
  pyext/swsscommon.i
Labels: Request_for_201811_branch, enhancement

#260 Move warm_restart enable/disable config to stateDB WARM_RESTART_ENABL…
  common/schema.h
  common/warm_restart.cpp
  common/warm_restart.h
  tests/warm_restart_ut.cpp
Labels: Request_for_201811_branch

#261 Force only supported commands on consumer table
  common/consumer_table_pops.lua
  tests/redis_piped_ut.cpp
  tests/redis_ut.cpp
Labels: enhancement

#242 Add support for WarmStart::setDataCheckState()
  common/warm_restart.cpp
  common/warm_restart.h
  tests/warm_restart_ut.cpp
Labels: Request_for_201811_branch, enhancement
