Repository sonic-net/sonic-swss-common, pull requests merged in 2021-08, with the labels that each got.

#510 [logger] Make map access thread safe and proper terminate thread
  common/concurrentmap.h
  common/logger.cpp
  common/logger.h
Labels: Enhancement

#514 Fix azure pipeline DownloadPipelineArtifact source branch
  .azure-pipelines/build-docker-sonic-vs-template.yml
Labels: ci

#523 [Flex Counters] Add a new field for FLEX_COUNTER_TABLE to indicate delay state
  common/schema.h
Labels: Request for 202106 branch
